prod:
  image: registry.cnode.fr/LifeworkWallet:1.0.1
  container_name: LifeworkWallet
  expose:
   - "5000"
  environment:
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    NODE_ENV: production

staging:
  image: registry.cnode.fr/LifeworkWallet:develop
  container_name: LifeworkWallet-staging
  expose:
   - "5000"
  environment:
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    DEBUG: "LifeworkWallet-*"

local:
  build: .
  container_name: LifeworkWallet-local
  ports:
    - "5000:5000"
  environment:
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    NODE_ENV: production

local-develop:
  build: .
  container_name: LifeworkWallet-local-develop
  ports:
    - "5000:5000"
  environment:
    SERVER_RENDERING: 1
    REDUX_DEVTOOLS: 0
    FRONTEND_SERVER_PORT: 5000
    DEBUG: "LifeworkWallet-*"
