export const TOGGLE_LEFTNAV = 'TOGGLE_LEFTNAV';
export const OPEN_LEFTNAV = 'OPEN_LEFTNAV';
export const CLOSE_LEFTNAV = 'CLOSE_LEFTNAV';
export const SET_API = 'SET_API';
export const SET_APP_BAR_DEPTH = 'SET_APP_BAR_DEPTH';
export const SET_INITIAL_RENDER_TIME = 'SET_INITIAL_RENDER_TIME';
