export const ADD_TO_WALLET = 'ADD_TO_WALLET';
export const REMOVE_FROM_WALLET = 'REMOVE_FROM_WALLET';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_WALLET = 'SET_WALLET';
export const UPDATE_TO_WALLET = 'UPDATE_TO_WALLET';
